#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Jun 14, 2019 09:46:41 PM IST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import DocDep_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    DocDep_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    DocDep_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font15 = "-family {DejaVu Sans} -size 10 -weight normal -slant"  \
            " italic -underline 0 -overstrike 0"
        font16 = "-family {DejaVu Sans} -size 10 -weight bold -slant "  \
            "italic -underline 0 -overstrike 0"
        font17 = "-family {DejaVu Sans} -size 14 -weight bold -slant "  \
            "roman -underline 1 -overstrike 0"
        font9 = "-family {DejaVu Sans} -size 10 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("1366x666+0+27")
        top.title("DocDep")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.41, rely=0.045, height=27, width=227)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(font=font17)
        self.Label1.configure(text='''Are You Depressed??''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.432, rely=0.09, height=21, width=162)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(font=font15)
        self.Label2.configure(text='''Its OK To ASK for HELP!!''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.439, rely=0.165, height=21, width=154)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(font=font16)
        self.Label3.configure(text='''Lets Start the test!!''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.469, rely=0.225, height=31, width=70)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(font=font9)
        self.Button1.configure(text='''START''')
        self.Button1.bind('<Button-1>',lambda e: DocDep_support.StartButton(e))

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.417, rely=0.3, height=21, width=225)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(text='''*press START when you are ready''')

        self.Text1 = tk.Text(top)
        self.Text1.place(relx=0.359, rely=0.39, relheight=0.111, relwidth=0.268)
        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(width=366)
        self.Text1.configure(wrap="word")

        self.Text2 = tk.Text(top)
        self.Text2.place(relx=0.307, rely=0.586, relheight=0.321, relwidth=0.378)

        self.Text2.configure(background="white")
        self.Text2.configure(font="-family {DejaVu Sans} -size 10")
        self.Text2.configure(selectbackground="#c4c4c4")
        self.Text2.configure(width=516)
        self.Text2.configure(wrap="word")

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.359, rely=0.36, height=21, width=84)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Instructions:''')

        self.Label6 = tk.Label(top)
        self.Label6.place(relx=0.307, rely=0.556, height=21, width=49)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(text='''Result:''')

if __name__ == '__main__':
    vp_start_gui()





